---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04  # Updated to the latest version
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Ensures latest GitHub Action version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py test"
    
      - name: Run Linter
        run: docker compose run --rm app sh -c "flake8 ."

      