---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04  # Updated from ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2  # Updated from v1 to v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@v4  # Updated from v2 to v4

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py test"

      - name: Run Linter
        run: docker compose run --rm app sh -c "python manage.py flake8"
