---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04  # Updated to the latest version
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Ensures latest GitHub Action version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Improves Docker performance

      - name: Run Tests
        run: docker compose up --exit-code-from app  # Runs app service with proper exit codes

      - name: Run Linter
        run: docker compose run --rm app sh -c "flake8 ."

      - name: Stop Services
        if: always()  # Ensures cleanup happens even if tests fail
        run: docker compose down
